# project link
https://credit-card-demo-akshat.streamlit.app/

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [2]:
train_df = pd.read_csv('fraudTrain.csv')
test_df = pd.read_csv('fraudTest.csv')

In [3]:
train_df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0


In [4]:
train_df.shape

(1296675, 23)

In [5]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype  
---  ------                 --------------    -----  
 0   Unnamed: 0             1296675 non-null  int64  
 1   trans_date_trans_time  1296675 non-null  str    
 2   cc_num                 1296675 non-null  int64  
 3   merchant               1296675 non-null  str    
 4   category               1296675 non-null  str    
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  str    
 7   last                   1296675 non-null  str    
 8   gender                 1296675 non-null  str    
 9   street                 1296675 non-null  str    
 10  city                   1296675 non-null  str    
 11  state                  1296675 non-null  str    
 12  zip                    1296675 non-null  int64  
 13  lat                    1296675 non-null  float64
 14  long                   129667

In [6]:
train_df.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [7]:
train_df['is_fraud'].value_counts()

is_fraud
0    1289169
1       7506
Name: count, dtype: int64

In [8]:
drop_cols = ['Unnamed: 0','trans_date_trans_time','cc_num','first','last','street','city','state','zip','dob','trans_num']

In [9]:
train_df.drop(columns=drop_cols, inplace=True)
test_df.drop(columns=drop_cols, inplace=True)

In [10]:
categorical_cols = train_df.select_dtypes(include='object').columns

C:\Users\aksha\AppData\Local\Temp\ipykernel_8280\606114575.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = train_df.select_dtypes(include='object').columns


In [11]:
for col in categorical_cols:
    le = LabelEncoder()

    combined = pd.concat([train_df[col], test_df[col]])

    le.fit(combined)

    train_df[col] = le.transform(train_df[col])
    test_df[col] = le.transform(test_df[col])

In [12]:
X_train = train_df.drop('is_fraud', axis=1)
y_train = train_df['is_fraud']

X_test = test_df.drop('is_fraud', axis=1)
y_test = test_df['is_fraud']

In [14]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
clf1=LogisticRegression(max_iter=1000)
clf1.fit(X_train,y_train)
pred1=clf1.predict(X_test)
print("Accuracy Score of Logistic Regression is:",accuracy_score(y_test,pred1))

Accuracy Score of Logistic Regression is: 0.9961401355721147


In [15]:
confusion_matrix(y_test,pred1)

array([[553574,      0],
       [  2145,      0]])

In [16]:
print(classification_report(y_test, pred1))

C:\Users\aksha\.conda\envs\ml\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


              precision    recall  f1-score   support

           0       1.00      1.00      1.00    553574
           1       0.00      0.00      0.00      2145

    accuracy                           1.00    555719
   macro avg       0.50      0.50      0.50    555719
weighted avg       0.99      1.00      0.99    555719



C:\Users\aksha\.conda\envs\ml\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\aksha\.conda\envs\ml\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [17]:
# Decision Tree
from sklearn.tree import DecisionTreeClassifier
clf2=DecisionTreeClassifier(random_state=42)
clf2.fit(X_train,y_train)
pred2=clf2.predict(X_test)
print("Accuracy Score of Decision Tree is:",accuracy_score(y_test,pred2))

Accuracy Score of Decision Tree is: 0.9937072513266597


In [18]:
confusion_matrix(y_test, pred2)

array([[550991,   2583],
       [   914,   1231]])

In [19]:
print(classification_report(y_test,pred2))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    553574
           1       0.32      0.57      0.41      2145

    accuracy                           0.99    555719
   macro avg       0.66      0.78      0.70    555719
weighted avg       1.00      0.99      0.99    555719



In [20]:
# Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
clf3=RandomForestClassifier(n_estimators=100,random_state=42)
clf3.fit(X_train,y_train)
pred3=clf3.predict(X_test)
print("Accuracy Score of Random Forest is:",accuracy_score(y_test,pred3))

Accuracy Score of Random Forest is: 0.9974195591656935


In [21]:
confusion_matrix(y_test, pred3)

array([[553186,    388],
       [  1046,   1099]])

In [22]:
print(classification_report(y_test,pred2))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    553574
           1       0.32      0.57      0.41      2145

    accuracy                           0.99    555719
   macro avg       0.66      0.78      0.70    555719
weighted avg       1.00      0.99      0.99    555719



In [13]:
features = [
    'amt',
    'lat',
    'long',
    'city_pop',
    'unix_time',
    'merch_lat',
    'merch_long'
]

X_train = train_df[features]
X_test = test_df[features]

In [14]:
from sklearn.ensemble import RandomForestClassifier
import joblib

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

joblib.dump(rf, "fraud_model_compressed.pkl", compress=9)

['fraud_model_compressed.pkl']

In [27]:
import sklearn
import scipy

print(np.__version__)
print(pd.__version__)
print(sklearn.__version__)
print(scipy.__version__)

2.4.4
3.0.2
1.8.0
1.16.3


In [28]:
import joblib
print(joblib.__version__)

1.5.3


In [23]:
import joblib

model = joblib.load("fraud_model.pkl")

print(model.feature_names_in_)

['amt' 'lat' 'long' 'city_pop' 'unix_time' 'merch_lat' 'merch_long']
